#!/bin/bash

if [[ "$1" == "" ]]; then
	echo "Set kubectl namespace context"
	echo "Usage: kubectl context <namespace>"
	echo "Available contexts: $(kubectl config view -o jsonpath='{.contexts[*].name}')"
	exit 1
elif [[ "$1" == "version" ]]; then
	echo "Version: 1.0.0"
	exit 0
else
	kubectl config use-context "$1"
	echo "Context set to $1"
fi
